name: CI

on:
  push:
    branches: [ master, win-build ]
  pull_request:
    branches: [ master ]

env:
  KALDI_ROOT: kaldi

jobs:
  java:
#    runs-on: windows-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout kaldi repo
        uses: actions/checkout@v2
        with:
          repository: kaldi-asr/kaldi
          path: kaldi

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - run: dir

      - name: Build
        run: make && make run
