name: CI

on:
  push:
    branches: [ master, win-build ]
  pull_request:
    branches: [ master ]

env:
  KALDI_ROOT: kaldi

jobs:
  java:
#    runs-on: windows-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout kaldi repo
        uses: actions/checkout@v2
        with:
          repository: kaldi-asr/kaldi
          path: kaldi

      - name: Kaldi compilation
        working-directory: kaldi/tools
        run: |
          sudo apt-get install -y sox gfortran
          extras/install_mkl.sh
          extras/install_openblas.sh
          extras/check_dependencies.sh
          make
          cd ../src
          ./configure --mathlib=OPENBLAS --shared --use-cuda=no
          make -j 10

#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.x'
#
#      - name: Build Python module
#        working-directory: python
#        run: python3 setup.py install --user --single-version-externally-managed --root=/

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - run: ls -al

      - name: Build Java library
        working-directory: java
        run: make
